### ISSUE TITLE
Please check requirements file.

### ISSUE THREAD

**Issue by NoWayBg** [InnoFang/what-digit-you-write#6]
I download your project and install requirements,After that run app.py
But there are some error happen.
ERROR: tensorflow 1.13.1 has requirement numpy>=1.13.3, but you'll have numpy 1.13.1 which is incompatible.
ERROR: tensorflow 1.13.1 has requirement protobuf>=3.6.1, but you'll have protobuf 3.2.0 which is incompatible.
ERROR: tensorflow-estimator 1.13.0 has requirement numpy>=1.13.3, but you'll have numpy 1.13.1 which is incompatible.
ERROR: tensorboard 1.13.1 has requirement protobuf>=3.6.0, but you'll have protobuf 3.2.0 which is incompatible.
ERROR: scipy 1.3.0 has requirement numpy>=1.13.3, but you'll have numpy 1.13.1 which is incompatible.
ERROR: pandas 0.25.0 has requirement numpy>=1.13.3, but you'll have numpy 1.13.1 which is incompatible.
ERROR: flask 1.1.1 has requirement Werkzeug>=0.15, but you'll have werkzeug 0.12.1 which is incompatible.
ERROR: tensorflow-gpu 1.14.0 has requirement numpy<2.0,>=1.14.5, but you'll have numpy 1.13.1 which is incompatible.
ERROR: tensorflow-gpu 1.14.0 has requirement protobuf>=3.6.1, but you'll have protobuf 3.2.0 which is incompatible.
ERROR: tensorflow-gpu 1.14.0 has requirement tensorboard<1.15.0,>=1.14.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: tensorflow-gpu 1.14.0 has requirement tensorflow-estimator<1.15.0rc0,>=1.14.0rc0, but you'll have tensorflow-estimator 1.13.0 which is incompatible.

**Comment by InnoFang** [comment]
Maybe you should try to reinstall `requirements` in a virtual environment.

**Comment by NoWayBg** [comment]
> Maybe you should try to reinstall requirements in a virtual environment.

Do you mean that I re-install requirements in virtual environment only.
I try but same error last time.
![can't run app](https://user-images.githubusercontent.com/34510549/63207397-59557400-c0ef-11e9-8f58-b686cf643148.jpg)

**Comment by InnoFang** [comment]
I have been tried to update my `requirements` file, you can try it again.
